services:
  ambev.dev.test.api:
    container_name: ambev_dev_test_api
    image: ${DOCKER_REGISTRY-}ambevdevtestapi
    build:
      context: .
      dockerfile: Ambev.Dev.Test.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ambev.dev.test.database:
    container_name: ambev_dev_test_database
    image: postgres:13

    environment:
      POSTGRES_DB: ambev_dev_test
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: d3v3l0p3r!
    ports:
      - "5432:5432"
    restart: unless-stopped
